import Link from "next/link";

const zones=["Centro y casco histórico","Estación AVE","Hospital Ernest Lluch","Barrios y urbanizaciones","Comarca de Calatayud","Zaragoza y aeropuerto"];
const steps=[{number:"01",title:"Indica la recogida",copy:"Escribe una dirección, un establecimiento o un punto conocido de Calatayud."},{number:"02",title:"Confirmamos el servicio",copy:"La central avisa a los profesionales disponibles según guardia y cercanía operativa."},{number:"03",title:"Sigue tu taxi",copy:"Recibe la confirmación y consulta el estado hasta que llegue a recogerte."}];

export default function Home(){return <main className="public-home">
  <div className="service-bar"><div className="shell"><span><i/> Central digital de taxi · Calatayud</span><span>Servicio local coordinado</span></div></div>
  <header className="site-header shell"><Link href="/" className="brand"><span className="brand-mark">PT</span><span>PideTaxi<span>Calatayud</span></span></Link><nav className="desktop-nav"><Link href="/pedir-taxi?tipo=ahora">Pedir taxi</Link><Link href="/pedir-taxi?tipo=reserva">Reservar</Link><Link href="/descargar-app">Descargar app</Link></nav><div className="header-actions"><Link href="/alta-taxista">Alta profesional</Link><Link className="header-link" href="/acceso">Acceso taxistas</Link></div></header>
  <section className="hero shell"><div className="hero-main"><span className="eyebrow">Movilidad local, coordinada en tiempo real</span><h1>Tu taxi en<br/><em>Calatayud.</em></h1><p className="hero-copy">Una central sencilla para pedir o reservar taxi, conectar con profesionales de la zona y saber en todo momento cómo avanza tu servicio.</p><div className="hero-actions"><Link className="button primary" href="/pedir-taxi?tipo=ahora">Pedir taxi ahora <span>→</span></Link><Link className="button secondary" href="/pedir-taxi?tipo=reserva">Programar reserva</Link></div><p className="trust-line"><span>✓</span> Sin registro para clientes <span>✓</span> Confirmación automática <span>✓</span> Pago directo al taxista</p></div>
  <aside className="dispatch-board" aria-label="Ejemplo de servicio coordinado"><header><span>Central Calatayud</span><b><i/> Operativa</b></header><div className="dispatch-route"><div><small>RECOGIDA</small><strong>Estación AVE Calatayud</strong><span>Acceso principal</span></div><i/><div><small>DESTINO</small><strong>Hospital Ernest Lluch</strong><span>2 pasajeros</span></div></div><div className="dispatch-status"><span>Taxi asignado</span><strong>Confirmación en directo</strong></div><footer><span>Servicio local</span><span>Red profesional</span><span>Seguimiento</span></footer></aside>
  </section>
  <section className="local-band"><div className="shell"><b>CALATAYUD</b><span>Paseo Cortes de Aragón</span><span>Puerta de Terrer</span><span>Estación AVE</span><span>Hospital</span></div></section>
  <section className="how shell"><div className="section-heading"><div><span className="section-kicker">Cómo funciona</span><h2>Directo, claro y sin llamadas innecesarias</h2></div><p>La plataforma organiza la solicitud sin sustituir el trato profesional entre cliente y taxista.</p></div><div className="steps professional-steps">{steps.map(step=><article className="step" key={step.number}><span className="step-number">{step.number}</span><h3>{step.title}</h3><p>{step.copy}</p></article>)}</div></section>
  <section className="coverage"><div className="shell coverage-grid"><div><span className="section-kicker">Zona de servicio</span><h2>Calatayud y su entorno</h2><p>Desplazamientos urbanos, estaciones, centros sanitarios, empresas, pueblos de la comarca y trayectos de larga distancia.</p><Link className="text-link" href="/pedir-taxi?tipo=ahora">Solicitar un servicio →</Link></div><div className="zone-list">{zones.map((zone,index)=><span key={zone}><i>{String(index+1).padStart(2,"0")}</i>{zone}<b>↗</b></span>)}</div></div></section>
  <section className="app-promo shell"><div className="app-promo-mark">PT</div><div><span className="section-kicker">Aplicación móvil</span><h2>Llévate la central contigo</h2><p>Descarga la versión para clientes o instálala desde el navegador. Siempre conectada al mismo servicio.</p></div><Link className="button primary" href="/descargar-app">Descargar app <span>↓</span></Link></section>
  <section className="driver-join shell"><div><span className="section-kicker">Profesionales del taxi</span><h2>Una herramienta para trabajar, no otra complicación.</h2><p>Solicita el alta profesional. Administración verificará la licencia y el vehículo antes de habilitar el panel y la aplicación exclusiva para taxistas.</p></div><div><Link className="button taxi-yellow" href="/alta-taxista">Solicitar alta</Link><Link className="driver-login" href="/acceso">Ya tengo acceso →</Link></div></section>
  <footer className="shell footer"><div className="brand"><span className="brand-mark">PT</span><span>PideTaxi<span>Calatayud</span></span></div><p>Central digital para el servicio profesional de taxi en Calatayud.</p><nav><Link href="/descargar-app">Descargar app</Link><Link href="/privacidad">Privacidad</Link><Link href="/aviso-legal">Aviso legal</Link><Link href="/informacion-plataforma">La plataforma</Link></nav></footer>
</main>}
